### ISSUE TITLE
Add Ubuntu example using cloud-init

### ISSUE THREAD

**Issue by carltonnorthern** [nutanix-cloud-native/packer-plugin-nutanix#109]
/kind feature

Ubuntu utilizing cloud-init does things a little differently and it would be good to have an example showcasing how this plugin would work.

I've gotten this to work already but have one issue with it.  It won't auto install without manually typing "yes" at the autoinstall prompt.  I used some of the code from https://github.com/andif888/packer-ubuntu-vsphere-iso and they have a boot_comand (https://github.com/andif888/packer-ubuntu-vsphere-iso/blob/master/ubuntu-2004.pkrvars.hcl) which bypasses this with vSphere.  But I can't figure out if this is something that is supported with this plugin or not.   I don't think it is.

**Comment by tuxtof** [comment]
Hello @carltonnorthern 

concerning `boot_command`  we already talk about that in #49 and #105 

using ubuntu cloud-image as a starting point is the best approach here

let me add an exemple

**Comment by tuxtof** [comment]
ubuntu example added in #110

**Comment by carltonnorthern** [comment]
Thank you!

**Comment by tuxtof** [comment]
Hello @darthVikes 

I'm fully agree with you and that's why there is an alternate example who use kickstart iso image
but for some OS it can be used out of the box due to the lack of boot_command support

there is no assumption we don't need/want boot_command, but the problem is that there is no keypress support in the Nutanix API console so we are not able to implement boot_command support in packer plugin right now

to keep it simple , it's not that we don't want to but that we can't ... for the moment

once the feature will be available from API side we'll get it up and running in no time.

please open a feature request support ticket on the Nutanix portal  , it will help to track and manage priorities

**Comment by darthVikes** [comment]
@tuxtof : Gotcha yah its hard to implement something if the APIs are not there.  Is there a main Feature request number that we could reference?  vs. just putting in a new ticket?   that way it will be easier to track # of people requesting the feature?

I was able to get the img_ working and have it boot from the iso, however, have some additional questions on that that I opened some new tickets on.

**Comment by tuxtof** [comment]
Hello @darthVikes @carltonnorthern  

we’ve decided to implement this boot_command feature using an internal method for now. We're preparing a tech preview, if you're interested in exploring it or providing feedback, feel free to reach out to me at christophe.jauffret@nutanix.com
