### ISSUE TITLE
Configurable Timeout for WaitForIP

### ISSUE THREAD

**Issue by wolfganghuse** [nutanix-cloud-native/packer-plugin-nutanix#82]
/kind bug

Windows Machine with DHCP needs more than the fixed 5min Timeout to report IP to PrismCentral.
Create an configuration option for timeout

**Comment by wolfganghuse** [comment]
There is a loop running 60 times, with 5seconds wait each.

**Comment by DiscoRiver** [comment]
I looked into how we might slot a configurable timeout into this, and I think the best approach would be to add an additional step to wait for the IP, rather than bundling it within the create step. Similar to this;

https://github.com/jetbrains-infra/packer-builder-vsphere/blob/bd2040307ce568a94887e41c644e20fa533f0fc7/common/step_wait_for_ip.go

I don't have enough experience with this code, or the cycles to implement right now, but I think this would be the best approach based on my limited research. 

Good luck!

**Comment by wolfganghuse** [comment]
@DiscoRiver Thanks for research, this is indeed a good solution. However, lets raise the fixed timeout now to 15min as a workaround for slow Windows Deployments until we implement the WaitForIP Step.

**Comment by tuxtof** [comment]
@DiscoRiver you can test with v0.4.0
